name: Publish
on:
  release:
    types: [published]
permissions: {}
jobs:
  go-get:
    name: go get
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release from proxy
        run: |
          curl -fsSL "https://proxy.golang.org/zombiezen.com/go/xcontext/@v/$(echo "$GITHUB_REF" | sed -e 's:^refs/tags/::').info"
