name: Test
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  nix:
    name: go test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Run tests
        run: go test -mod=readonly -race
