name: Test
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  nix:
    name: go test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes ca-derivations impure-derivations
      - name: Run tests
        run: nix flake check --print-build-logs
  windows:
    name: go test (Windows)
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v3.2.1
        with:
          go-version: "1.19.1"
      - name: Run tests
        run: go test -race
